from enum import StrEnum


class ErrorCode(StrEnum):
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    EMAIL_TAKEN = "EMAIL_TAKEN"
    REFRESH_TOKEN_NOT_VALID = "REFRESH_TOKEN_NOT_VALID"
    REFRESH_TOKEN_REQUIRED = "REFRESH_TOKEN_REQUIRED"
    INVALID_GOOGLE_TOKEN = "INVALID_GOOGLE_TOKEN"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
