/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReaderRouteImport } from './routes/reader'
import { Route as OutlineRouteImport } from './routes/outline'
import { Route as ExportRouteImport } from './routes/export'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'

const ReaderRoute = ReaderRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const OutlineRoute = OutlineRouteImport.update({
  id: '/outline',
  path: '/outline',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/editor': typeof EditorRoute
  '/export': typeof ExportRoute
  '/outline': typeof OutlineRoute
  '/reader': typeof ReaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/editor': typeof EditorRoute
  '/export': typeof ExportRoute
  '/outline': typeof OutlineRoute
  '/reader': typeof ReaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/editor': typeof EditorRoute
  '/export': typeof ExportRoute
  '/outline': typeof OutlineRoute
  '/reader': typeof ReaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/editor' | '/export' | '/outline' | '/reader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/editor' | '/export' | '/outline' | '/reader'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/editor'
    | '/export'
    | '/outline'
    | '/reader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  EditorRoute: typeof EditorRoute
  ExportRoute: typeof ExportRoute
  OutlineRoute: typeof OutlineRoute
  ReaderRoute: typeof ReaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outline': {
      id: '/outline'
      path: '/outline'
      fullPath: '/outline'
      preLoaderRoute: typeof OutlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  EditorRoute: EditorRoute,
  ExportRoute: ExportRoute,
  OutlineRoute: OutlineRoute,
  ReaderRoute: ReaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
